# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Holde/snake_for_real/snake_for_real.cache/wt [current_project]
set_property parent.project_path C:/Users/Holde/snake_for_real/snake_for_real.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Holde/snake_for_real/snake_for_real.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/7Segment_Display_Interface.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Generic_counter.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Master_State_Machine.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Multiplexer_4way.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Navigation_State_Machine.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Score_Counter.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Snake_control.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Target_Generator.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/VGA_Driver.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/VGA_Interface.v
  C:/Users/Holde/snake_for_real/snake_for_real.srcs/sources_1/imports/new/Master_Game.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Holde/snake_for_real/snake_for_real.srcs/constrs_1/imports/new/Snake_Constr.xdc
set_property used_in_implementation false [get_files C:/Users/Holde/snake_for_real/snake_for_real.srcs/constrs_1/imports/new/Snake_Constr.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Master_Game -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Master_Game.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Master_Game_utilization_synth.rpt -pb Master_Game_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
